# Generated by Django 3.0.6 on 2022-03-20 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('specialist', 'clinic', 'day_of_week')},
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_date', models.DateField()),
                ('time_slot', models.IntegerField(choices=[(0, '09:00 – 09:30'), (1, '10:00 – 10:30'), (2, '11:00 – 11:30'), (3, '12:00 – 12:30'), (4, '13:00 – 13:30'), (5, '14:00 – 14:30'), (6, '15:00 – 15:30'), (7, '16:00 – 16:30'), (8, '17:00 – 17:30')])),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.Patient')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.Specialist')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.Type')),
            ],
        ),
    ]
