# Generated by Django 3.0.6 on 2022-04-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0005_auto_20220322_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='sch_from',
            field=models.TimeField(verbose_name='Time from'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sch_to',
            field=models.TimeField(verbose_name='Time to'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('specialist', 'a_date', 'a_time', 'clinic')},
        ),
    ]
