# Generated by Django 3.0.6 on 2022-04-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0006_auto_20220402_1919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
